### ISSUE TITLE
Feature Request: show metadata on result page

### ISSUE THREAD

**Issue by pingu8007** [markusfisch/BinaryEye#102]
I would like to see BinaryEye show not only data but also information of barcode itself, such as code type (QR code, code39/128, EAN13 or more) and redundancy level of QR code.
I'm migrating from zxing barcode scanner to BinaryEye, and lacking of those stop me go any further.

Or, is there any developer option allowing me get those metadata?

**Comment by markusfisch** [comment]
Sorry, no, there are no hidden options right now. But the code type is already displayed directly below a barcode's content:
![screencap-20200319102337](https://user-images.githubusercontent.com/485246/77052046-88f19500-69cc-11ea-8330-a6c259b07221.png)

Of course, it's possible to show all of the metadata of the read barcode as it is provided by ZXing. Expect this to be in the next version. It's just a little more work than just showing the data because I would also save it in the history so you can see it later too.

**Comment by markusfisch** [comment]
Added in https://github.com/markusfisch/BinaryEye/commit/2b1d711168b2a29ec53c2a7ad3fd4ff768ea293d
