### ISSUE TITLE
Why do versions after 1.24.0 have "access precise location only in the foreground" enabled?

### ISSUE THREAD

**Issue by jg777** [markusfisch/BinaryEye#109]
Why do versions after 1.24.0 have "access precise location only in the foreground" enabled? Why does this app all of a sudden need this permission? Please fix this.

**Comment by markusfisch** [comment]
Good question.

Because according to the docs, [WifiManager.getConfiguredNetworks](https://developer.android.com/reference/android/net/wifi/WifiManager#getConfiguredNetworks()) requires `ACCESS_FINE_LOCATION` and `ACCESS_WIFI_STATE`. Please see here:
https://developer.android.com/reference/android/net/wifi/WifiManager#getConfiguredNetworks()

The change was introduced by this commit: https://github.com/markusfisch/BinaryEye/commit/276fcccc465c8b8b1637b71ecca02c5d6bc1413f

So `ACCESS_FINE_LOCATION` is required to add a WiFi network from a barcode that contains WiFi credentials (usually a QR Code). The app only asks for this permission when you scan a barcode that contains WiFi credentials and it's perfectly fine to deny the permission if you don't want to the app to be able to add the WiFi network.

As a side note, starting with Android Q, it's no longer possible to add a WiFi network directly anymore. Instead, an app can only make "suggestions" that the system may or may not use to connect to a WiFi. Worse, if the system decides to eventually connect to such a suggested network and you deinstall the app afterwards, you'll loose the credentials for the network. See:
https://developer.android.com/reference/kotlin/android/net/wifi/WifiManager#addNetworkSuggestions(kotlin.collections.MutableList)
