### ISSUE TITLE
Only scans up and down, not sideways

### ISSUE THREAD

**Issue by TheLastProject** [markusfisch/BinaryEye#112]
When auto rotate is disabled, the app will only scan the barcode if it is oriented normally or upside down, not when scanning it sideways. I've attached a video (in GIF format due to GitHub limitations) showing the issue, in case my description is insufficiently clear.

![binaryeye_rotation_issue](https://user-images.githubusercontent.com/1885159/81475039-cbd02c00-9209-11ea-9988-25f08a944afb.gif)

Device: Fairphone 3
Android version: 9
App version: 1.26.0

**Comment by markusfisch** [comment]
Well, this is because ZXing doesn't support reading rotated one dimensional barcodes, unfortunately 😞 

Interestingly, there is code that _would_ rotate an input image (if `TRY_HARDER` is set, which you can do since [1.25.0](https://github.com/markusfisch/BinaryEye/releases/tag/1.25.0) in settings, search for "Optimize reader for accuracy, not speed") in [OneDReader](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/oned/OneDReader.java#L57):

```java
  // Note that we don't try rotation without the try harder flag, even if rotation was supported.
  @Override
  public Result decode(BinaryBitmap image,
                       Map<DecodeHintType,?> hints) throws NotFoundException, FormatException {
    try {
      return doDecode(image, hints);
    } catch (NotFoundException nfe) {
      boolean tryHarder = hints != null && hints.containsKey(DecodeHintType.TRY_HARDER);
      if (tryHarder && image.isRotateSupported()) {
        ...
```

But since [LuminanceSource.isRotateSupported()](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/LuminanceSource.java#L101) is always `false` and it's descendant [PlanarYUVLuminanceSource](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/PlanarYUVLuminanceSource.java) doesn't overwrite this, it will *always* be false for images from Binary Eye because the camera frame is given ZXing as a `PlanarYUVLuminanceSource` object.

And since `PlanarYUVLuminanceSource` is final, we can't simply subclass it to implement the required [LuminanceSource rotateCounterClockwise()](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/LuminanceSource.java#L118).

**Comment by TheLastProject** [comment]
I guess at this point the obvious question is: Is there a reason `PlanarYUVLuminanceSource` needs to be used? Is there no other output format for the camera frame that does support rotation?

**Comment by markusfisch** [comment]
Not as far as I know. The camera image comes in YUV format, and `PlanarYUVLuminanceSource` is the object to be used for this type of data. ZXing offers only a couple alternative `LuminanceSource` implementations and none implements `LuminanceSource.isRotateSupported()` unfortunately.

But that doesn't mean all is lost. Since Binary Eye already needs to rotate the camera frame when the orientation of the camera (usually landscape) doesn't match the orientation of the device, it would be possible to just run a second pass with the rotated camera image.

The only problem is: it would cost half the performance and it's useless for other barcodes (e.g. ZXing can read QR Codes in every orientation).

But I still think it's worth a try ...

**Comment by markusfisch** [comment]
Version 1.29.0 adds a setting to enable vertical scanning of 1D barcodes:
https://github.com/markusfisch/BinaryEye/releases/tag/1.29.0

1.29.0 is currently in beta on Google Play (you can opt-in and out anytime and go back to the production version):
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

It's a setting (and it's off by default) because adding the ability to scan 1D barcodes vertically means that every other frame is automatically rotated. This doesn't matter for 2D barcodes which ZXing can read in any orientation. But for 1D barcodes that ZXing can only read in horizontal orientation, only half of all video frames are useful if the setting is activated (because the barcode is vertical on the other half). That means scanning 1D barcodes may take a bit longer on not so good devices. On a very good device, it doesn't matter all that much because enough frames can be processed in a very short time.
