### ISSUE TITLE
Feature Request: Aiming box or line

### ISSUE THREAD

**Issue by oijn** [markusfisch/BinaryEye#117]
Find BinaryEye very useful for scanning different barcodes.

Some products have labels with multiple different barcodes next to each other - and BinaryEye will decode whichever barcode the camera focuses on first - which may not be the barcode wanted.

Some other barcode scanning apps have either an aiming box or aiming line that can be used to restrict or prioritize the area that it tries to identify a barcode.  Some other apps even allow the aiming box dimensions to be modified by pinch-n-drag and some allow control over the camera zoom.

Having a BinaryEye feature that provided something like that would be appreciated.

Something that no other barcode scanning app does at the moment - is the ability to take a single photo of a complex label and then point-to and decode selected barcodes.  Would allow a single capture of a complex label and allow multiple barcode decodes improving efficiency.

**Comment by markusfisch** [comment]
Well, an aiming box would certainly help when there are multiple barcodes directly next to each other. And scanning only a section of the camera frame also improves performance especially for low end devices.

On the other hand requires an aiming box to aim more precisely which is why I didn't implement it so far. I thought it'd be easier to not have to move the barcode into a box. And the app can use the full camera resolution to decode a barcode (which can be important for some barcodes like PDF417 on devices with a bad camera).

But Binary Eye already allows control over the camera zoom (either by using the slider on the bottom of the screen or by just swiping up and down) and this can be used to narrow the view until only one barcode is in the camera view.

Also, if you take a picture of the product with multiple barcodes on it with your default camera app and then share this image, there should be an entry "Decode barcode" with the Binary Eye icon in the share menu. Then, Binary Eye shows you an aiming box over your image and you can move and zoom/pinch the barcode you want into the aiming box.

**Comment by oijn** [comment]
Thanks for the reply.  Privacy Friendly QR Scanner - has a easy box and aiming line - though it cannot be resized.  Once captured - it shows a small thumbnail and a line through what it decoded.  Maybe it could be a feature able to be turned-on/off via settings.  Some people would find it useful - others maybe not.  I understand your reasoning.

Thanks - I didn't know about the share image feature.  That is very useful - I'll definitely use it in future.  Though for some of the labels I have - without being able to resize the box it still decodes unintended barcodes.

I have a label which I could send you a photo of - that has 8 barcodes within a few inches.  It has serial numbers and MAC addresses so something I wouldn't want out in public (Its actually an Intel NUC box label).  I could send directly to you - so you can see the type of labels I'm referring to if you think that would be useful.

Thx.

**Comment by markusfisch** [comment]
https://github.com/markusfisch/BinaryEye/commit/fcac0add8b08f0efa90bf162b75d5b7a5321b566 adds an additional small circular button that allows you to define a region of interest by dragging it around.

This feature is available from Version 1.30.0 which is now in beta (don't worry you can always go back to the production version):
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

Or directly from here:
https://github.com/markusfisch/BinaryEye/releases/tag/1.30.0

**Comment by oijn** [comment]
Thanks - much appreciated - the implementation works well.
