### ISSUE TITLE
V1.31 flashes camera briefly for 4 times before crashing

### ISSUE THREAD

**Issue by wshyang** [markusfisch/BinaryEye#126]
Hi Sir,

I love your app 😊 

However on a new Redmi Note 9 phone the app has been failing to initialize. It would show the camera interface briefly and flicker for 4 times before finally terminating. How to fix this issue?

**Comment by markusfisch** [comment]
Sorry for the inconvenience 😬 Did you install the app with F-Droid or with Google Play?

I know it's odd but the F-Droid build doesn't work on some devices (if you care about the details see https://github.com/markusfisch/BinaryEye/issues/111 and https://github.com/markusfisch/BinaryEye/issues/113). I'm trying to fix this but the problem is with F-Droid 😞 

So, in the meantime, I'd recommend to install from Google Play or directly from GitHub here:
https://github.com/markusfisch/BinaryEye/releases/tag/1.32.0

**Comment by ankur-lakhmara** [comment]
good app but app has been failing to initialize  .

**Comment by monolifed** [comment]
I have this problem with 1.34 google play version (also with fdroid version)
