### ISSUE TITLE
Provide a way to disable the screen crop.

### ISSUE THREAD

**Issue by jtagcat** [markusfisch/BinaryEye#128]
So you click the crop button. It captures a reasonable amount of the screen. You click it again to disable, but instead you discover it's whatever-size-you-want.

But how do you get rid of it? My instinct was to drag it to the bottom right, (seeing it magically disappear and reset, maybe with a chat-bubble-like drag-to-the-x (but to the corner inside the bubble instead,) but instead it caused #127

**Comment by markusfisch** [comment]
Sorry for the inconvenience. You remove the ROI if you move the crop button to the (horizontal or vertical or absolute) center of the screen 😉 

I thought it would be quite obvious because getting close the center axis would make (at least) one ROI dimension 0. But moving it to the screen edges is also a perfectly valid strategy 🤔

**Comment by markusfisch** [comment]
Now, dragging the handle to one of the screen corner will remove the ROI too 😉 

See https://github.com/markusfisch/BinaryEye/commit/e86cf9d2cc5d59a42453622ed4eb2e7bc36355cc
