### ISSUE TITLE
Not scan big QR

### ISSUE THREAD

**Issue by OmlineEditor** [markusfisch/BinaryEye#144]
I scan from the monitor screen.
your application cannot scan this code. SecScanQR - this application a competitor can scan.
the problem seems to be different pixel widths for squares. 1 pixel difference.
![notscan](https://user-images.githubusercontent.com/13348933/98275632-e52e1700-1fa5-11eb-87b8-8efddf569f24.PNG)

**Comment by markusfisch** [comment]
Sorry for the late answer, and sorry for the inconvenience 😬 

Unfortunately, I cannot reproduce this problem as I can read this image with Binary Eye without problems:

<img src="https://user-images.githubusercontent.com/485246/98470887-ea2ed880-21e8-11eb-8c5c-ad66a007207a.png" width="320" alt="scan"/> <img src="https://user-images.githubusercontent.com/485246/98470892-eef38c80-21e8-11eb-9b88-2637d7e72c08.png" width="320" alt="read"/>

Or did you mean scanning this QR Code with the camera? If so, please try again in landscape mode without restricting scanning area to make the most out of the camera image. I was able to scan this code this way without too much hassle.

**Comment by OmlineEditor** [comment]
I cannot scan from the monitor screen. it always shows me different numbers, but not the code
![1](https://user-images.githubusercontent.com/13348933/98876458-64808680-248f-11eb-8d86-c565735e041e.jpg)

**Comment by markusfisch** [comment]
The reason for this is that the QR Code you try to read has so many tiny modules (dots) that they blur together in the camera frame which accidentally makes a simpler, random one-dimensional barcode 😬 Binary Eye tries to read all the different types of barcodes in the camera frame and so this can happen if the odds are just right. Which isn't very likely usually - you just seem to hit a rare case in which this isn't so unlikely it seems.

Now, there are two things you can do:

First, you could remove the cropping limiter and make Binary Eye scan the _whole_ screen. This means there are more pixels in the camera frame what makes a correct detection more likely.

Next, you could tap in the middle of the QR Code when scanning to make the camera focus on that spot. This will result in a sharp image what's also good for detection.

For demonstration, here I scan the code from above with my old Fairphone 2 (because it really hasn't a great camera):

![screenrecord-20201112141413](https://user-images.githubusercontent.com/485246/98946283-fcb05700-24f3-11eb-9b77-de261e8560c3.gif)

**Comment by OmlineEditor** [comment]
if I scan without cropping the image then it turns out to recognize the full text. It is very strange that the image is the same, but if you crop the view then the QR code cannot be recognized. you can check the code and fix the problem. The scan should be the same. cropping the image is just a more convenient way for me. The scan should be the same.

**Comment by markusfisch** [comment]
Well, the reason the QR Code is recognized _without_ cropping is that the QR Code covers more pixels in the full camera frame as opposed to just a section of it.

For example, if a camera frame has a width of 100 pixels, and a code has 100 dots in one direction, then we can read this code only if the code covers the full width of the camera frame. Only then every dot is represented in the pictures.

Now, if we move back a bit so that the code covers only 80 pixels of our camera frame, we cannot decode the code because 20 of the dots of the code are missing from the input image.

So the problem is not really the cropping but that if we use just a section of the camera image we have less resolution what means less information. And so, there's nothing I could fix in the code 😉
