### ISSUE TITLE
Feature Request: Add a quick settings tile

### ISSUE THREAD

**Issue by iwismer** [markusfisch/BinaryEye#160]
Adding a quick settings tile makes it super quick to get to open the app from anywhere. I just thought it would be a nice to have extra.

**Comment by markusfisch** [comment]
Good idea 👍

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/e6d9d548660968477dcfe0ea10630de5119d6278

Will be available soon 😄

**Comment by timk** [comment]
I really like this function however for me on a OnePlus 7T with Android 12 (OxygenOS) the quick settings button takes me to the Android "App Info" dialog from where I have to take a second step and press "Open".

OS version: Android 12
App version: 1.60.3

![Screenshot_2023-06-11-13-59-52-14_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/markusfisch/BinaryEye/assets/814119/153a7308-e48b-4162-9564-3fe7b67d1f9f)

**Comment by markusfisch** [comment]
Thanks a lot for reporting this!Unfortunately, I can't reproduce this at the moment because I don't have a device with with OxygenOS at hand. But I'll look into it as soon as possible.Very weird 🤔Am 11.06.2023 22:01 schrieb timk ***@***.***>:
I really like this function however for me on a OnePlus 7T with Android 12 (OxygenOS) the quick settings button takes me to the Android "App Info" dialog from where I have to take a second step and press "Open".
OS version: Android 12
App version: 1.60.3
