### ISSUE TITLE
Add informations about the code

### ISSUE THREAD

**Issue by Nico207** [markusfisch/BinaryEye#17]
Hi,
it could be great if we can have some informations about the scanned code.
After a scan, you could display his type (Code39, Code128GS1, Datamatrix... ), his lenght, his raw content...

Thanks !

**Comment by markusfisch** [comment]
Hi, the app currently shows just the raw contents of the scanned code. Or do you want a hex dump as it was mentioned in #7?

Showing further details is a good idea.

**Comment by markusfisch** [comment]
Added in https://github.com/markusfisch/BinaryEye/commit/c56fa39c15a904f02c54ea4d25068b1dee485a42

**Comment by Nico207** [comment]
Seeing the hexa code in addition to the ASCII code would be great.
This would us allow to see the separation code FNC1 for GS1 codes (among others).

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/1e3f1c553cd78e351d669f236bfe0192375586c6

Available in 1.5.0 currently in Beta. You may opt-in for Beta builds here:
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

**Comment by Nico207** [comment]
Thanks for the link, but I don't have (and don't want) a Google Account.
Why not put an apk file with beta versions in github (like releases) ?

**Comment by markusfisch** [comment]
Fair enough:
https://github.com/markusfisch/BinaryEye/releases/tag/1.5.0

**Comment by Nico207** [comment]
Great, thank you !

I tried with an "EAN-128 GS1" (`[10]1[21]2`), but I don't see the character FNC1 (ASCII code 29) which should finish the part "10" of the code...

Result
`31 30 31 32 31 32`

Expected
`31 30 31 29 32 31 32`

**Comment by markusfisch** [comment]
Well, I'm afraid `FNC1` is swallowed by ZXing 😬

Have a look:
https://github.com/zxing/zxing/blob/0cf3b9be71680f50c90a71ca26ce0d33664b0dd6/core/src/main/java/com/google/zxing/oned/Code128Reader.java#L341

Since Binary Eye doesn't explicitly give the hint `DecodeHintType.ASSUME_GS1` because it really should read all possible barcode types, `FNC1` isn't included in the result.

Maybe I should really use [Result.getRawBytes()](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/Result.java#L78) for the hex dump instead of [Result.getText()](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/Result.java#L71). Will try.

Anyway, by investigating this issue I found that the way the hexdump is generated was flawed. So there's a an update (https://github.com/markusfisch/BinaryEye/releases/tag/1.5.1) but that doesn't solve this issue for now unfortunately.
