### ISSUE TITLE
Possibility to open the correct application, depending on the content of the code read

### ISSUE THREAD

**Issue by Nico207** [markusfisch/BinaryEye#18]
Hi,

After scaning a barcode, can you add a button to open the application in connection with the code read.

Examples :

 - if the code contain an URL → the button can open the webbrowser
 - if the code start with `mailto:` → the button can open the mail client
 - if the code is a vCard `BEGIN:VCARD` → the button can open the contact app
 - ... 

You can see some other one on this page : [https://github.com/zxing/zxing/wiki/Barcode-Contents](https://github.com/zxing/zxing/wiki/Barcode-Contents)

Thanks !

**Comment by markusfisch** [comment]
Yes, that would make sense of course. As soon as I find the time to implement it.

**Comment by realrufans** [comment]
Urmmmm I think this has been implemented ?

**Comment by markusfisch** [comment]
No, not yet. At the moment, the app only knows how to open URLs.

**Comment by realrufans** [comment]
Okay . Check out #19 might be helpful 😛

**Comment by airon90** [comment]
```WIFI:S:SSID;T:AUTH;P:PASSWORD;;``` should connect to a wifi connection named SSID, password as PASSWORD and authentication AUTH (WEP/WPA/...)

There are many other, I will write them down this evening

**Comment by airon90** [comment]
- [ ] ```tel:PHONENUMBER``` should open dialer with ```PHONENUMBER```
- [ ] ```smsto:PHONENUMBER:MESSAGE``` should open an SMS app and create a SMS to ```PHONENUMBER``` with ```MESSAGE``` as message
- [ ] ```mailto:EMAIL?subject=SUBJECT&body=TEXT``` should open an email app and create a new email to ```EMAIL``` (mandatory) with ```SUBJECT``` as subject and ```TEXT``` as body 
- [ ] ```BEGIN:VEVENT```
```SUMMARY:EVENTSUMM```
```DESCRIPTION:EVENTDESC```
```LOCATION:EVENTLOC```
```DTSTART:EVENTTIME1```
```DTEND:EVENTTIME2```
```END:VEVENT```
should add an event in the calendar app with ```EVENTSUMM``` as the name of the event, ```EVENTDESC``` as description of the event, ```EVENTLOC``` as location of the event, ```EVENTTIME1``` and ```EVENTTIME2``` as start and end of the event (format: "```YYYYMMDD```T```HHMMSS```Z")
- [ ] ```BEGIN:VCARD```
```VERSION:2.1```
```N:NAMESURNAME```
```TEL;HOME;VOICE:HOMENUMBER```
```TEL;WORK;VOICE:WORKNUMBER```
```EMAIL:EMAILADDR```
```ORG:ORGANIZATION```
```TITLE:PERSONJOB```
```BDAY:YYYYMMDD```
```ADR:STREETADDR```
```URL:URLADDR```
```END:VCARD```
should add a new contact with ```NAMESURNAME``` as the name of the person, ```HOMENUMBER``` as phone number of person's home and ```WORKNUMBER``` as phone number of person's work, ```EMAILADDR``` as his/her email address, ```ORG``` and ```TITLE``` as position (```TITLE```) of his/her job in ```ORG```, ```STREETADDR``` as his/her home street address and ```URLADDR``` as his/her website.

Maybe there are more codes to support.

**Comment by molikuner** [comment]
Hey, I started implementing this feature in my fork. I'm currently having trouble finding a good way to add a new WIFI via Intents. I just found a method that allows to configure the network in the app itself, which I personally don't like/prefer.
Does anyone know a good way to solve this problem with Intents? Start an Intent for the settings app with special extras?

**Comment by molikuner** [comment]
@airon90 by the way, `tel:` should work out of the box, as it is currently implemented.

**Comment by markusfisch** [comment]
@molikuner Here's how the original ZXing Android app adds a new WiFi from a QR code: https://github.com/zxing/zxing/blob/master/android/src/com/google/zxing/client/android/wifi/WifiConfigManager.java#L107

**Comment by molikuner** [comment]
@markusfisch Thank you for this reference. I have already found this implementation of WIFI support. If you agree, I would implement it in the next few days. The app would need some additional [permissions](https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml#L31):
```xml
  <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
```

After looking at the calendar and contacts, I'm not quite sure if you should fully support them. The problem is that many tags in these vFormats become very complex. The ZXing Android app implements only partial support (e.g. [calendar](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/client/result/VEventResultParser.java#L32)).
The contacts are a bit special, because you don't have to implement a real parser. There is a way to share a `.vcf` file with the contacts and import it. To open the contact afterwards, you just need to give the app an additional permission to search for that contact. But keep in mind that you probably don't want to do this because the contact app imports the specified file asynchronously and you can't be sure if the contact has already been added or will be added in the next few seconds. This means that the only nice implementation would be a parser for the contacts.

**Comment by jas14** [comment]
For what it's worth, just opened #40 , which adds a WiFi connect button and should also make it easier to add actions for other custom data types mentioned above (e.g. contacts, events)
