### ISSUE TITLE
Unable to "forget" WiFi entry added via BinaryEye

### ISSUE THREAD

**Issue by jmtysonjr** [markusfisch/BinaryEye#197]
Greetings,

I created a WiFi network connection profile -- _skynet-guest_ -- by way of scanning a QR code using _Binary Eye_ and the resulting entry will not allow for "forgetting" the connection profile.  The only option provided is "Disconnect".
![WiFi-connection-profile-options](https://user-images.githubusercontent.com/11633584/120323609-ab12c280-c2b3-11eb-8279-ab5fae06aacd.jpg)

As a result, I am unable to "Forget" the connection profile.
![WiFi-connection-details](https://user-images.githubusercontent.com/11633584/120323607-aa7a2c00-c2b3-11eb-925d-6e87ef6e7036.jpg)

The WiFi profile also does not show up under the "Saved networks".
![WiFi-saved-networlks](https://user-images.githubusercontent.com/11633584/120323610-ab12c280-c2b3-11eb-99fc-0765dfc025a5.jpg)

I tried clearing _Binary Eye's_ cache and storage to no avail; still no option to _forget_ the connection profile.

**Comment by markusfisch** [comment]
Sorry, turns out this is because network suggestions cannot be removed by the user 🙈 For whatever reason Google found this useful. Anyway, I just added an item in settings to remove all network suggestions that were added by Binary Eye to get rid of networks added by Binary Eye.

Version 1.43.0 should become available shortly in Google Play. F-Droid should update tomorrow. And you can get the new version directly from GitHub here:
https://github.com/markusfisch/BinaryEye/releases/tag/1.43.0

**Comment by jmtysonjr** [comment]
Thanks Markus, this resolved the issue on my end by removing the entry.

**Comment by markusfisch** [comment]
You're welcome! And thanks for pointing me at the issue!

**Comment by geo909** [comment]
Forgive me for resurrecting this. The suggested solution works but it is a little bit of a nuclear option. I have saved a bunch of wifi logins using binary eye; once I scanned a qr code with an invalid password for one wifi network, and then I had to wipe them all because of this issue. Is there any way to selectively forget network suggestions?

Thank you very much, and great job on the app.

**Comment by markusfisch** [comment]
Yes, network suggestions can be selectively removed, and it really makes a lot of sense to offer a listing to select the ones you want to remove instead of clearing everything 😬  Sorry this isn't already possible - I have only implemented the minimum solution for now.

The next release will offer a listing to select which one you want to remove.

**Comment by geo909** [comment]
Thanks for the quick fix, Markus! Keep up the good work.

**Comment by JacobKochems** [comment]
from https://github.com/markusfisch/BinaryEye/issues/293#issuecomment-1331993689:
> About removing/editing individual network suggestions (also discussed in #197): unfortunately it's not possible to get a list of the suggestions an app has added before see_no_evil There is just [getCallerConfiguredNetworks](https://developer.android.com/reference/android/net/wifi/WifiManager#getCallerConfiguredNetworks()) but that is only available from API level 31 on. So this might only be possible for newer devices.

How about this one:
from https://developer.android.com/reference/android/net/wifi/WifiManager#getNetworkSuggestions():
> Get all network suggestions provided by the calling app.

It's available from API level 30 (Android 11) on.

**Comment by markusfisch** [comment]
Oh my, yes, you're right, that's the correct function! I don't know how I could have missed that 🙈 

Although this would also only work for Android 11+. Which means that there's probably a gap for Android 10 because you can add network suggestions there (because [addNetworkSuggestions](https://developer.android.com/reference/android/net/wifi/WifiManager#addNetworkSuggestions(java.util.List%3Candroid.net.wifi.WifiNetworkSuggestion%3E)) is available from API level 29 on), but not list them 🤔

**Comment by JacobKochems** [comment]
> Which means that there's probably a gap for Android 10 because you can add network suggestions there (because [addNetworkSuggestions](https://developer.android.com/reference/android/net/wifi/WifiManager#addNetworkSuggestions(java.util.List%3Candroid.net.wifi.WifiNetworkSuggestion%3E)) is available from API level 29 on), but not list them.

Yes, I noticed that too. This would leave Android 10 users in UX limbo. But look at it this way: From Android 11 onward this problem will outgrow itself. And on the bright side it "only" effects Android 10, because earlier versions make use of the old global network config namespace functionality.

**Comment by JacobKochems** [comment]
@markusfisch I just had another look at https://developer.android.com/reference/android/net/wifi/WifiManager#enableNetwork(int,%20boolean)

The documentation states that it is: "Deprecated in API level 29". I always thought that the deprecation rules in general are: "Mark it as deprecated in this version and remove it in the next one. Going by this, this function should still work in API level 29.

Could you maybe change instances of

`if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {`

in 'WifiConnector.kt' to

`if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.Q) {`

???

If so, that would close the gap.

**Comment by markusfisch** [comment]
Yes, you are right! 👍 Changed in https://github.com/markusfisch/BinaryEye/commit/527b7a6a5913dc117f07a4225b7c64f134be3bc6

For existing installations (on Q) I will keep the "Clear network suggestions" option in preferences for Q so it's still possible to remove them there. Before Q this option isn't visible.

**Comment by markusfisch** [comment]
No, no, you're totally right! I just forgot to check `parse()` too 🙈 Thanks a lot for making me aware of it! 👍 

(Hopefully) fixed in https://github.com/markusfisch/BinaryEye/commit/72b8924574fad55463c2ef54151ca579810ba9e5

And I welcome everybody to second guess my work! After all this is what Open Source is for 😉

**Comment by markusfisch** [comment]
Thanks, and no problem, I'm a bit of a pedant myself 😉 And it's always nice to get feedback!
