### ISSUE TITLE
Internet availability may not be being verified in project

### ISSUE THREAD

**Issue by amazuerar** [markusfisch/BinaryEye#211]
Dear Developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within android apps. As a result of this we identified that there is a missing validation of Internet availability within the project which is needed since some network operations are being performed in the application. 

As you might know, a device may be connected to a network but may not have Internet connection. Therefore it is recommended for the app to identify whether the device is connected to a network having Internet connectivity before performing a network operation.

In order to address this issue we recommend you to:

1. Obtain representation of the capabilities of an active network, they are typically obtained through `NetworkCallback#onCapabilitiesChanged(Network, NetworkCapabilities)` or `ConnectivityManager#getNetworkCapabilities(Network)`
2. See: https://developer.android.com/reference/android/net/NetworkCapabilities
3. See: https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_INTERNET
4. See: https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_VALIDATED

**Comment by markusfisch** [comment]
Well, I have a very different opinion on this 😬 

My argument is that it's simply impossible to know if you can connect to server without connecting to a server. Of course you can use `NET_CAPABILITY_INTERNET`, but that really only tells you that `google.com` is available. What may be the case in this or that network. But it doesn't tell you anything about the address you are interested in.

Since the only network request Binary Eye can make is to send a scanned code to a custom address, it may very well be harmful to limit these requests to the availability of `google.com`. You may just want to reach your Raspberry Pi in your private network, for example.

**Comment by amazuerar** [comment]
@markusfisch I really appreciate your quick reply and your feedback :smiley:   It is useful and helps improving my research and enhance some heuristics. I still have some remaining and related issues to share, could I open them separately or would it better to have a brief description within this thread?

**Comment by markusfisch** [comment]
As you like, whatever fits best. You're welcome 😄
