### ISSUE TITLE
Feature Request: Support MECARD contact info

### ISSUE THREAD

**Issue by suuppl** [markusfisch/BinaryEye#217]
Hi, great app! Thank you.

While playing around I noticed that i can't add MECARD contact info. I used [this](https://www.computerbild.de/fotos/QR-Codes-zum-Ausprobieren-6131009.html#1) code to test.

<details>
    <summary>Code Content</summary>

    MECARD:N:COMPUTERBILD LESERSERVICE;TEL:04034723933;URL:www.computerbild.de;EMAIL:redaktion@computerbild.de;ADR:Axel-Springer-Platz 1 20350 Hamburg;;

</details>

Possibly related to [#73](https://github.com/markusfisch/BinaryEye/issues/73#issuecomment-788222812), although my phone (Huawei CLT-L29) runs on Android 10 (EMUI 10.0.0, Build 10.0.0.185)

I have version 1.44.1 installed, which is the latest version at the time of writing.

When scanning the code I can search the content with a search engine of my choice but I can't add it to my contacts, which I'd expect.

**Comment by markusfisch** [comment]
Sorry, Binary Eye doesn't support the MECARD format yet 😬 

But since MECARD can (hopefully) very easily be transformed to the VCARD format, I just added such a transformation: https://github.com/markusfisch/BinaryEye/commit/3c8c0737c4091a506a67d46d486ff5fcc1d8e3d2

So the next version should support MECARD too.

**Comment by suuppl** [comment]
Nice! Thank you :D

**Comment by markusfisch** [comment]
Version 1.45.0 with support for MECARD should become available shortly.
