### ISSUE TITLE
Suggestion of encoding images in bar code.

### ISSUE THREAD

**Issue by peerzadaaabid** [markusfisch/BinaryEye#22]
Hi
Of course, I found the binary eye quite interesting but I want to improve it further by the implementation of the following suggestion.
It should encode the images also in the barcode, I mean It should be able to generate a barcode which can store images too.

Thanks
With regards
@peerzadaabid

**Comment by markusfisch** [comment]
Well, that would only be possible with _very_ small images. Due to the nature of barcodes, the capacity is quite limited. Every line or dot (and also every blank space in between) represents just _one_ bit. So depending on the color depth of an image, you'd need a multiple of the size of the image for a barcode containing that image.

If you like to explore further, please have a look at the Wikipedia article for QR codes:
https://en.wikipedia.org/wiki/QR_code

**Comment by markusfisch** [comment]
Recently I had the opportunity to look into that topic a bit more. And indeed, it's possible to encode small (and heavily compressed) images in (quite big) QR codes. A QR code has a maximum storage capacity of 2,953 bytes. So, if you can compress your image within that limit (for example by using a low resolution and/or quality level), you can put it into a QR code.

Since Binary Eye supports reading binary data from QR codes, you would be able to read such a QR code and save its contents in a file. Binary Eye wouldn't show you the image, though. At the moment, Binary Eye doesn't do much interpretation of read content.

If you like to play around, I'd recommend using [qrencode](https://github.com/fukuchi/libqrencode) and perhaps [Image Magick](https://imagemagick.org).
