### ISSUE TITLE
binary data can't save

### ISSUE THREAD

**Issue by noormohammedb** [markusfisch/BinaryEye#238]
Can't save binary data after scanning qr code, Previously it was working.
After scanning the data is showing in table like hex and raw unicode but not working save button below, it can share but it's sharing the hex values not file

**Comment by markusfisch** [comment]
Sorry for the inconvenience 🙈 You're right, the button is broken in the latest version. Will fix asap.

**Comment by markusfisch** [comment]
Thanks for filing an issue about that! 👍 

Fixed in https://github.com/markusfisch/BinaryEye/commit/47c252ab18c7c3bb8439b764527c006ed7d6e6f5

Version 1.46.2 is already being processed on Google Play and should become available within the next few hours.

If you want to update right now, you could update directly from GitHub:
https://github.com/markusfisch/BinaryEye/releases/tag/1.46.2
