### ISSUE TITLE
iCal events result in wrong time

### ISSUE THREAD

**Issue by travelalpaca** [markusfisch/BinaryEye#264]
Using this example iCalendar event from https://datatracker.ietf.org/doc/html/rfc5545#section-3.6 

       BEGIN:VCALENDAR
       VERSION:2.0
       PRODID:-//hacksw/handcal//NONSGML v1.0//EN
       BEGIN:VEVENT
       UID:19970610T172345Z-AF23B2@example.com
       DTSTAMP:19970610T172345Z
       DTSTART:19970714T170000Z
       DTEND:19970715T040000Z
       SUMMARY:Bastille Day Party
       END:VEVENT
       END:VCALENDAR

In the above example, DTSTART has a time of 170000Z, which is 17:00 UTC, which is 5:00 PM GMT.  Other apps that process iCal events will send this data to calendar apps, and the start time of the event will automatically be adjusted to my local time.  For example, if I were in New York, the time of the event might read 12:00 because of the -5 hour UTC offset in winter or 13:00 because of -4 hour UTC offset in the summer.  This works the same for all combination of apps that read iCal and calendar apps that make events except...

... this isn't what happens with BinaryEye.  With BinaryEye, if I scan a QR code with the above iCal data, something goes wrong with the time or timezone, and the calendar app makes the start time 17:00 _in my local timezone_.  This shouldn't happen.  The only scenario in which start time should actually be 17:00 is when the user is actually in the UTC timezone, which is a small minority of people on the planet.  I don't know exactly what BinaryEye is doing to somehow lock-in the nominal 17:00 start time instead of allowing the start time to be auto-adjusted to the local time equivalent of 17:00 UTC.

I wrote all of that specifying _start time_ for simplicity.  The _end time_ is affected in the same way.

**Comment by markusfisch** [comment]
Sorry, yes, this is a bug 🙈 

Apparently the timezone isn't evaluated although there's code for it.

**Comment by markusfisch** [comment]
Well, as always with time zones, it's more complex than one would think 😉 

Android's [Calendar interface](https://developer.android.com/reference/android/provider/CalendarContract.EventsColumns#DTSTART)  accepts only an integer specifying "the time the event starts in UTC millis since epoch" (which means since https://en.wikipedia.org/wiki/Unix_time). So no timezone is given here.

But the date from the VCalendar can contain a timezone, of course. So it's necessary to convert this date from the given timezone to the local timezone, where the device is in. The original code in Binary Eye assumed this conversion would happen automatically once a date(time) with a timezone is parsed. But this was wrong.

Hopefully it's fixed now in https://github.com/markusfisch/BinaryEye/commit/e1b39356596e244be20a12139da83b2bf304243d
