### ISSUE TITLE
Some QR codes cause crash

### ISSUE THREAD

**Issue by meiMingle** [markusfisch/BinaryEye#321]
This is the text used to generate this QR code`com.taobao.arthas.boot.ProcessUtils.findJavaHome(ProcessUtils.java:222)`
When I scan it with BinaryEye, BinaryEye freezes for a few seconds and crashes.
![qrcode_cause_crash](https://user-images.githubusercontent.com/39942874/202996402-d9c210ac-4d56-4fb5-9890-6e5bfd021ff6.png)
Also causing this problem is the QR code generated by the following string：
`com.taobao.arthas.boot.ProcessUtils.findJavaHomeProcessUtils.java222`
![image](https://user-images.githubusercontent.com/39942874/202998880-9d915425-7437-4b02-9b71-6956ec4b13fa.png)

`com.taobao.arthas.boot.ProcessUtils.findJavaHomeProcessUtilsppppppppppppppppppp000`
![image](https://user-images.githubusercontent.com/39942874/202998963-06751fc0-9f8e-4d83-b9ae-b1d6f029484f.png)

**Comment by markusfisch** [comment]
Thanks for reporting! 👍 Good catch!

Fixed in https://github.com/markusfisch/BinaryEye/commit/6449d9962d4c2a3848215d203bcb29a6ba5675e9

A new version, 1.56.3, is on its way on Google Play and should become available within the next few hours. F-Droid updates usually after a day or so. If you want, you can also update directly from GitHub Releases:
https://github.com/markusfisch/BinaryEye/releases
