### ISSUE TITLE
Binary Eye 1.58 - Feedback

### ISSUE THREAD

**Issue by bovirus** [markusfisch/BinaryEye#348]
@markusfisch 

Pelase check screenshot

![20230120_124910-new](https://user-images.githubusercontent.com/1262554/213722516-414dd461-f1d4-4ca0-992d-530412e07c2c.jpg)

Possible improvements

Set smaller font size for link (now seem too big)

There is an area on GUI that seems not used.
If you can use it improve usability.

**Comment by markusfisch** [comment]
Well, it would be possible to use a so-called [Autosize TextView](https://developer.android.com/develop/ui/views/text-and-emoji/autosizing-textview) for the content, but I'm afraid it wouldn't make things better 🙈

Sure, in this sample, on your device, a smaller text size would make the URL not wrap. But when the URL is a couple of characters longer, when should it break to not become unreadable? Now I think finding that limit is probably a matter of taste and what works for one person might be annoying to another.

Then, this text field can hold *any* content from any barcode. So it would almost always have a very different text size. This would make the layout always look different, which can be bit irritating.

About the unused area: The hexdump always groups 8 bytes in one line so that the characters in the text column can be easily assigned. Of course, we could increase the text size to make it cover the whole space. But that again would lead to a pretty inconsistent layout. Font size has a semantic meaning. If we read something in a bigger font, we think it's more important. But that wouldn't be the case here.

**Comment by bovirus** [comment]
#[markusfisch

Thanks for the reply explaing the technical reason.

Please close the issue.
