### ISSUE TITLE
ASCII art is not displayed correctly

### ISSUE THREAD

**Issue by Grafenea** [markusfisch/BinaryEye#356]
I was doing some tests with QR Codes, one of them was to use them to store ASCII art, however when I scan them in Binary Eye they are displayed incorrectly.

![Screenshot_20230215-195922](https://user-images.githubusercontent.com/121762566/219372349-e1546d42-0db1-450a-aac6-22c3569ea49d.jpg)

For comparison, look at the correct display.

![Screenshot_20230215-195858](https://user-images.githubusercontent.com/121762566/219372517-1a4820f4-ddcb-4b8d-89d0-45bc87f1824f.jpg)

Here the sample Qr Code in case you wanted to solve the problem.

![test](https://user-images.githubusercontent.com/121762566/219372875-baacfbe7-c332-4aae-a46e-d6635890313e.png)

**Comment by markusfisch** [comment]
What a funny idea! 😉 I like this 👍 

The reason for the distortion is that Binary Eye is using a monospace font where the space character is just as wide as any other character. So, when I copy the contents of your sample into a code black, which is also using a monospace font by default, your sample looks like this:

```
⠀           (\ __ /)
              (UwU)
       ＿ノ ヽ ノ＼＿ 
    /　`/ ⌒Ｙ⌒ Ｙ　 \
 ( 　(三ヽ人　 /　 　|
|　ﾉ⌒＼ ￣￣ヽ　 ノ
ヽ＿＿＿＞､＿＿／
          ｜( 王 ﾉ〈 
           /ﾐ`ー―彡\ 
          |╰    ❨      ╯|   
          |       /\       |
          |      /  \      |
          |    /     \     |
```

Usually, and traditionally, ASCII Art is made for monospaced fonts because this is where it's usually used (in terminals, source code, things like that). Making ASCII Art in a proportional font makes the art font-specific because it then only works with certain fonts. Here's a more elaborate explanation:
https://en.wikipedia.org/wiki/ASCII_art#Non_fixed-width_ASCII

Of course, if you convert this sample to a monospace version, it won't work for other apps that use a proportional font for the scanned contents like the one in the second screenshot 😬

**Comment by Grafenea** [comment]
Thanks for the help, the only thing I think that could solve this problem is after the scan, in the three-point menu there is an option to change the font. But I think it's a waste of time to have this option just to display an ASCII art correctly.
