### ISSUE TITLE
Empty pop-up message on Binary Eye version 1.8.1

### ISSUE THREAD

**Issue by chrisbarth01** [markusfisch/BinaryEye#36]
#### Expected behavior 
I expected the app to either encode the content or tell me that I inputted an invalid selection, format, or anything that was wrong. 

---

#### Actual behavior 
When I select the format I want (I selected PDF_417), select the size, add the content I want to encode, and click on 'ENCODE' button, an empty pop-up messages is shown. Leaving me confused about what actually happened while trying to create the barcode

---

#### How to reproduce 
- Download, install and launch the latest version of the app
- Grant the required permission and scan a barcode 
- Click on the '+' icon at the top right corner of the screen.
- Select the 'PDF_417' format.
- Select the size in pixels as 896*896.
- Input anything as the content. 
- Click on the 'ENCODE' button
- Observe the bug.

---

Device: Gionee f100s 
Android version: v6.0
App version: v1.8.1

---

#### Recording of the bug
![20190614_164546](https://user-images.githubusercontent.com/49325171/59522422-92425400-8ec6-11e9-8c3a-fc0445cb5cb4.gif)

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/902215f064615d74c008c43a3db6eeeba4e873db

The empty message came directly from ZXing's [Exception](https://github.com/markusfisch/BinaryEye/blob/master/app/src/main/kotlin/de/markusfisch/android/binaryeye/fragment/BarcodeFragment.kt#L54). Now, if the Exception's message is empty, a generic error message is shown.
