### ISSUE TITLE
Main layout is broken

### ISSUE THREAD

**Issue by inglar** [markusfisch/BinaryEye#361]
Main layout seems to be broken. Crop button is out of screen. @markusfisch, could you fix that?

<img alt="Screenshot_2023-03-07-12-27-37-61_a0aa29124cd502a33492270b004311eb" src="https://user-images.githubusercontent.com/60971712/223473622-055c55c4-0e1e-4f94-afcb-c1ad5a2dae3e.jpg" width="50%" />

App version 1.59.0
"Show cropping limiter" option is on.
Device/OS info
<img alt="Screenshot_2023-03-07-12-28-24-18_fc704e6b13c4fb26bf5e411f75da84f2" src="https://user-images.githubusercontent.com/60971712/223473662-5a4e701c-576e-40ee-a3e8-dac96c9048f8.jpg" width="50%" />

**Comment by markusfisch** [comment]
Ah, I know this is a bit tricky, sorry for that 🙈  I _think_ it's not broken - the crop button is just at the edge of the cropping window that is allowed to cover the whole screen. Since the crop bottom is always centered on the edge of the cropping window, this means the button can be half off the screen.

But you can still move it! It may just be a little bit tricky with Android's new gesture navigation. Because the button is so near to the edge of the screen, you need to move the button vertical first to avoid triggering Android's back gesture 😬 I know this isn't ideal.

**Comment by inglar** [comment]
@markusfisch, thanks. Vertical movement do the job!
