### ISSUE TITLE
Please don't hardcode the search engine

### ISSUE THREAD

**Issue by avoidr** [markusfisch/BinaryEye#37]
Users prefer different search engines, so please let them provide their own query URL.

Especially the current search engine is controversial, especially in the FOSS world. There are many people who would like to avoid this service (and would most appreciate if they aren't lead there by accident!).

Please take this into consideration and thank you!

P.S.: As for issue #35—the searching for EAN_13 codes—there is OpenFoodFacts.org (and OpenBeautyFacts.org and OpenPetFoodFacts.org); free and open databases of information on food products. Maybe this could be a good idea.

**Comment by markozajc** [comment]
Agreed. Making Google the default is okay for most people, but allowing configuration of an alternative search engine would be much appreciated.

**Comment by markusfisch** [comment]
Makes sense. So instead of simply opening Google, version 1.9.1 shows a dialog for the user to pick a suitable search engine for the scanned item (see https://github.com/markusfisch/BinaryEye/commit/d73ea341c02d78ef8a84320717c3ed9e7ab359bb)

Apart from Google, I just added DuckDuckGo, Qwant and OpenFoodFacts.org, OpenBeautyFacts.org and OpenPetFoodFacts.org, of course.

Version 1.9.1 is currently in beta and should become available in the next few minutes. Opt-in here:
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

You may also try the APK directly from here:
https://github.com/markusfisch/BinaryEye/releases/tag/1.9.1

**Comment by avoidr** [comment]
Thank you, that was quick!

Yes, that's a good solution, thank you ☺
