### ISSUE TITLE
Passing scan back to another app.

### ISSUE THREAD

**Issue by Flatc4t** [markusfisch/BinaryEye#435]
Hi Markus, 
I'm having problems with the new update (looked for documentation here and in general but couldn't find anything that helped). Previously I used the code below to retrieve the scanned code back into my App but it now no longer works. As best as I can tell, the 
result.data?.getStringExtra("SCAN_RESULT") string is null. Reverting the app back to an older version gets it back working again. Has there been a change to how this works (and if so, what would I need to modify)?

Thanks
Rick

val scanDocketButton = findViewById<Button>(R.id.scanButton)
        scanDocketButton.setOnClickListener {
            val intent = Intent("com.google.zxing.client.android.SCAN")
            intent.putExtra("SCAN_MODE", "QR_CODE_MODE")
            getResult.launch(intent)
        }
    }

    // Define the activity result contract
    val getResult = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
        if (result.resultCode == RESULT_OK) {
            val scannedText = result.data?.getStringExtra("SCAN_RESULT")
            val intent = Intent(this, xxxxx::class.java).apply {
            }
            startActivity(intent)
        }
    }

**Comment by markusfisch** [comment]
Hi Rick, sorry, this was indeed a bug in Binary Eye! Thanks for filing an issue about that!

Since the format was migrated from a simple string to an (internal) object, the return intent could no longer work for other apps (that did not know this object class, of course) 🙈 This is fixed in https://github.com/markusfisch/BinaryEye/commit/0d4f536f71b0fa91732c9b8083a8c6642d526adb

There will be a new version soon!

**Comment by Flatc4t** [comment]
Thanks Markus
I now have no need to fear updates 😁 - well, based on my capability of
coding, I do, but I can pretend for a while.

Rick
