### ISSUE TITLE
Read from screen

### ISSUE THREAD

**Issue by Wilker-a** [markusfisch/BinaryEye#64]
the idea is that there would be a button to minimize the app and start looking for readable codes on the screen (will probably need permission to 'draw over other apps'), so i can go to a webpage and show the code, while the app shows a visual cue that this is a readable code and therefore i can select to go back to the app to see it.

a positive point of this would be that i can do stuff such as sending an OTP key to Aegis*, for example, without having to actually download any images to anywhere other than the browser cache or having the code pass through the clipboard.  
###### \* sending OTP, TOTP keys and alike would require a way of generating an url for the protocol to send totp stuff, but that is a topic for another issue

a con of this though is the permission for seeing the screen, which might worry some people, i think, so i don't know if that is a good idea...

what do you think? :3

**Comment by markusfisch** [comment]
Well, for one thing, you can share any image (with Binary Eye) from any website by simply long pressing it. The browser will open a context menu from which you can choose "Share" and pick "Binary Eye".

So I think reading the screen would be pretty much overkill because the Android way is to simply share the image 😉 

What you can do with a screenshot, too, by the way. So if you're not a website and there's no share button for the code you want to read, you can always make a screenshot (hold down the power and volume-down buttons for a couple of seconds) and share that.

That said, there's one thing I'd like to add for scanning from (shared) images: the possibility to manually zoom and cut the code you want Binary Eye to read from a shared image. This may be handy if the code is very small on the shared image or when there are multiple codes on the image. 

On the other hand, you can already zoom and cut images with Google Photos (and similar apps) so this feature would just make scanning from an image a tiny bit simpler for some special cases.

**Comment by Wilker-a** [comment]
about the share button, i didn't think of that, thank you for remembering \^\^

about the screenshot though, that is the thing i want to avoid too, same with downloading and the clipboard.

but i understand that. thank you anyway \^\^ 

>That said, there's one thing I'd like to add for scanning from (shared) images: the possibility to manually zoom and cut the code you want Binary Eye to read from a shared image. This may be handy if the code is very small on the shared image or when there are multiple codes on the image.

i want to suggest a logic for that but i think that is a thing for another issue \^\^' is there a thread/issue open for that yet?

**Comment by markusfisch** [comment]
Not yet, but you're welcome to create one, of course 😄
