### ISSUE TITLE
Feature Request: Use "View Barcode" to ask about "FileName"

### ISSUE THREAD

**Issue by metadings** [markusfisch/BinaryEye#88]
Look. You do "Create Barcode", QR_CODE, 640x640, ..., then you have "View Barcode" and you can either share something, or you do press the "Save" action button.

I do want you to have such a "View Barcode", where you directly ask "What Filename?" You should also display the Address, if you do "View Barcode"! Then you do press the "Save" action button or share (where you really shouldn't expect anyone to have Amaze! SaveAs) !! (I tried a lot of file managers now, really no one is just "Save as...")

( You may also do type something really very very long long text-text-text into the Content box... If you do so, the text moves the "Encode" button down my Android... I always need to press the "back" button, to find this "Encode" button. You should move the "Encode" button to the action bar above!!!  )

**Comment by markusfisch** [comment]
Listen. I don't think saving the barcode as a file is a primary use case. Of course, it would be possible to put an input field above or below the barcode. But I guess you wouldn't expect the keyboard to open automatically. Because then, you wouldn't see much of the barcode. Which is, I guess, what most people would expect after generating a barcode. So you would have to tap the input field so the keyboard comes up. Well, that's just as good as tapping "Save" right now. It's just one tap and you can write a file name !!

So, personally, I don't see any benefit in putting an input field beside the generated barcode. I understand saving barcodes as a file is your primary use case. But you can do it with the app as it is with exactly as much taps.

Why do you care about "Save as" from Amaze when there's a "Save as file" button in the app? I don't expect anyone to have the Amaze File Manager. That's why there is a "Save as file" button.

I'm aware of the "Encode" button getting unreachable with long contents and I will fix this with the next version.

**Comment by metadings** [comment]
Yeah, I just thought that "shared_barcode.png" is a bit boring, stupid name... I'm renaming this immediately to QR_CODE.tel_+49178___4863.png ... You're right, this would pop up this stupid keyboard... Well perhaps there should be another Pane or Panel or how do you call a View ?

**Comment by metadings** [comment]
Yo, what about the "focus", can you make a View, initially not being focused on a text box?

**Comment by markusfisch** [comment]
Using the barcode contents for the file name is a very good idea! Will be in the next version 👍 

Although I'm wondering how you're seeing "shared_barcode.png" because that is the name of the private file. Don't you use the "Save as" action item in the upper right corner?

View is the right term 😉 

And yes, it's very well possible to not focus the input field initially but that would just add another tap if you want to use the input field 😬

**Comment by metadings** [comment]
> Although I'm wondering how you're seeing "shared_barcode.png" because that is the name of the private file.

Yeah, I believe this is because... I don't know :smile_cat: 
I've just pressed "SaveAs" and "OK", ~~I don't know where this was saved~~, this is saved as `.png`, If I'm going to enter a filename, it is correctly saved to `/storage/emulated/0/Download`.

Look, actually I do have two Feature Requests for you:
- In the Settings/Options view, there should be a "Preferred Folder to save to"
- Scan Multiple Barcodes, at once

You do also need to replace `:/\` and so on for the filename, I would also prefer a prefix like `QRCODE`! Keep up the good work :+1:

**Comment by metadings** [comment]
Hey Hallo Markus Fisch. This is 2020-04-09!

I do want to make a screenshot of this:
I've made a BusinessCard with multiple, 4 QR-Codes on it. I do want to copy this screenshot, without each one of the barcodes. So that I have the following Images
- the First with all 4 barcodes reading (upper left one first hehe) tel:0178---4863
- the Second Image with 3 QR-codes... reading geo:48.6319,9.3554?z=11
- the Third Image 2 barcodes, reading https://github.com/metadings
- and the Fourth Image with ... I don't know anymore... mailto

What I don't have is any QR-Barcode Scanner which is reading all 4 Codes at once!
Instead of always reading just the First one tel:0178, and without reading the other 3 codes!

**Comment by markusfisch** [comment]
What you want to do is https://en.wikipedia.org/wiki/VCard

All of that information should go into _one_ QR Code only.
